//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatoca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booked
    {
        public string cpnr { get; set; }
        public string gid { get; set; }
        public string bdate { get; set; }
        public string btime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Gymsession Gymsession { get; set; }
    }
}
