//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatoca
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hatoca_inlamningEntities : DbContext
    {
        public hatoca_inlamningEntities()
            : base("name=hatoca_inlamningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Booked> Bookeds { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Gymsession> Gymsessions { get; set; }
    }
}
